- name: translation
  color: "0e8a16"
  description: "Translation work and localization"
- name: docs
  color: "0052cc"
  description: "Documentation changes"
- name: versioning
  color: "5319e7"
  description: "Versioned docs snapshots and release notes"
- name: style
  color: "fbca04"
  description: "Style guide and formatting"
